//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballStadion.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FootballStadiumEntities : DbContext
    {
        public FootballStadiumEntities()
            : base("name=FootballStadiumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customer_to_Rooms> Customer_to_Rooms { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Rezerv_to_Rooms> Rezerv_to_Rooms { get; set; }
        public virtual DbSet<Rezerve> Rezerves { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Stadium> Stadia { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
    }
}
